"""
Django settings for proyecto_john project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============= CONFIGURACIÓN DE AMBIENTE =============
# Determina el ambiente actual: 'local', 'staging', 'production'
# Render detectado automaticamente (Render pone RENDER=true por defecto)
ENVIRONMENT = config('ENVIRONMENT', default='local')

# Si Render esta activo, forzar modo produccion
RENDER = config('RENDER', default=False, cast=bool)
if RENDER:
    ENVIRONMENT = 'production'
    PRODUCTION_HOST = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')

# Configuración basada en ambiente
DEBUG = ENVIRONMENT == 'local'
PRODUCTION = ENVIRONMENT == 'production'
STAGING = ENVIRONMENT == 'staging'

# ============= SEGURIDAD Y CONFIGURACIÓN BÁSICA =============
if RENDER:
    # Render: dominio automatico + hosts del .env
    SECRET_KEY = config('SECRET_KEY')
    _extra_hosts = [host.strip() for host in config('ALLOWED_HOSTS', default='').split(',') if host.strip()]
    _render_hosts = [PRODUCTION_HOST, '.onrender.com'] if PRODUCTION_HOST else ['.onrender.com']
    ALLOWED_HOSTS = _render_hosts + _extra_hosts
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if not host.startswith('.')]
elif PRODUCTION:
    SECRET_KEY = config('SECRET_KEY')  # Requerida en producción
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='tu-dominio.com').split(',')
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host != 'localhost']
else:
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-change-in-production')
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver').split(',')
    CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mi_app',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mi_app.auditoria.AuditoriaRequestMiddleware',
]

# Middleware condicional basado en ambiente
if PRODUCTION or STAGING:
    # Solo en producción/staging
    MIDDLEWARE.append('mi_app.utilities.middleware.RateLimitMiddleware')

ROOT_URLCONF = 'proyecto_john.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mi_app.context_processors.environment_context',  # Agregar contexto del ambiente
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_john.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if ENVIRONMENT == 'local':
    # Desarrollo local - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif ENVIRONMENT in ['staging', 'production']:
    # Producción/Staging - PostgreSQL
    # Soporte para DATABASE_URL (Render lo inyecta automaticamente al linkear la BD)
    import urllib.parse
    _db_url = os.environ.get('DATABASE_URL', '')
    if _db_url:
        _url = urllib.parse.urlparse(_db_url)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': _url.path[1:],
                'USER': _url.username,
                'PASSWORD': _url.password or '',
                'HOST': _url.hostname,
                'PORT': _url.port or 5432,
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('DB_NAME', default='proyecto_john'),
                'USER': config('DB_USER', default='django_user'),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'HOST': config('DB_HOST', default='localhost'),
                'PORT': config('DB_PORT', default='5432'),
                'OPTIONS': {
                    'sslmode': 'require' if PRODUCTION else 'prefer',
                } if PRODUCTION else {},
            }
        }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'  # Español Colombia

TIME_ZONE = 'America/Bogota' if ENVIRONMENT == 'local' else config('TIME_ZONE', default='UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de archivos estáticos por ambiente
if PRODUCTION:
    # WhiteNoise para servir archivos estáticos en producción
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = False
else:
    # Configuración de desarrollo
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============= CONFIGURACIONES ESPECÍFICAS POR AMBIENTE =============

# Logging
if PRODUCTION:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'logs' / 'django_error.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }
    # Crear directorio de logs si no existe
    os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Email configuration
if PRODUCTION:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST')
    EMAIL_PORT = config('EMAIL_PORT', cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
else:
    # Email backend de consola para desarrollo
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Cache configuration
if PRODUCTION:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Security settings for production
if PRODUCTION:
    # Render usa proxy reverso con SSL termination
    if RENDER:
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ============= CONFIGURACIÓN DE LA APLICACIÓN =============

# Configuraciones específicas de la app de créditos
CREDITS_CONFIG = {
    'MAX_LOAN_AMOUNT': config('MAX_LOAN_AMOUNT', default=10000000, cast=int),
    'MIN_LOAN_AMOUNT': config('MIN_LOAN_AMOUNT', default=100000, cast=int),
    'DEFAULT_INTEREST_RATE': config('DEFAULT_INTEREST_RATE', default=15.0, cast=float),
    'MAX_PAYMENT_DAYS': config('MAX_PAYMENT_DAYS', default=30, cast=int),

    # Configuración de reportes
    'ENABLE_ADVANCED_REPORTS': config('ENABLE_ADVANCED_REPORTS', default=PRODUCTION, cast=bool),

    # Configuración de backups
    'AUTO_BACKUP_ENABLED': config('AUTO_BACKUP_ENABLED', default=PRODUCTION, cast=bool),
    'BACKUP_RETENTION_DAYS': config('BACKUP_RETENTION_DAYS', default=30, cast=int),
}

# Configuración de auditoría
AUDIT_CONFIG = {
    'ENABLE_AUDIT_LOG': config('ENABLE_AUDIT_LOG', default=True, cast=bool),
    'AUDIT_RETENTION_DAYS': config('AUDIT_RETENTION_DAYS', default=365, cast=int) if PRODUCTION else 30,
}