# Generated by Django 6.0.2 on 2026-03-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('total_prestado__gte', 0)), name='cliente_total_prestado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('total_pagado_historico__gte', 0)), name='cliente_total_pagado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_cumplimiento__gte', 0), ('tasa_cumplimiento__lte', 100)), name='cliente_tasa_cumplimiento_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('dias_mora_promedio__gte', 0)), name='cliente_dias_mora_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0)), name='cliente_rating_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('numero_cuota__gt', 0)), name='cuota_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_original__gt', 0)), name='cuota_monto_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('interes_normal__gte', 0)), name='cuota_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_principal__gte', 0)), name='cuota_monto_pagado_principal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_interes__gte', 0)), name='cuota_monto_pagado_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_mora__gte', 0)), name='cuota_monto_pagado_mora_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pendiente__gte', 0)), name='cuota_monto_pendiente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_pagado__gte', 0), ('porcentaje_pagado__lte', 100)), name='cuota_porcentaje_pagado_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('numero_cuota__gt', 0)), name='cuota_rapida_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('monto_original__gt', 0)), name='cuota_rapida_monto_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('interes_normal__gte', 0)), name='cuota_rapida_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pendiente__gte', 0)), name='cuota_rapida_monto_pendiente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_principal__gte', 0)), name='cuota_rapida_monto_pagado_principal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_interes__gte', 0)), name='cuota_rapida_monto_pagado_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado_mora__gte', 0)), name='cuota_rapida_monto_pagado_mora_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotarapida',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_pagado__gte', 0), ('porcentaje_pagado__lte', 100)), name='cuota_rapida_porcentaje_pagado_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gt', 0)), name='pago_monto_pagado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_principal__gte', 0)), name='pago_monto_principal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_interes__gte', 0)), name='pago_monto_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_mora__gte', 0)), name='pago_monto_mora_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pagoprestamorapido',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gt', 0)), name='pago_prestamo_rapido_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gt', 0)), name='prestamo_monto_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('interes_porcentaje__gte', 0)), name='prestamo_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prestamorapido',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='prestamo_rapido_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='prestamorapido',
            constraint=models.CheckConstraint(condition=models.Q(('interes_porcentaje__gte', 0)), name='prestamo_rapido_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prestamorapido',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gte', 0)), name='prestamo_rapido_monto_pagado_no_negativo'),
        ),
    ]
