# Generated by Django 6.0 on 2025-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_prestamo_cuota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['numero_cuota']},
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='interes_mora',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='monto',
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago_esperada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='interes_mora_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='interes_normal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
