# Generated by Django 4.2.30 on 2026-09-13 18:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_cliente_cliente_total_prestado_no_negativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='capital_antes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de capital del préstamo justo antes de este pago.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='capital_despues',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de capital del préstamo justo después de este pago.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='capital_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo de capital vivo. Fuente única de verdad — no se reparte en las cuotas.', max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='interes_acumulado_sin_pagar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Interés de períodos anteriores que quedó sin pagar y se arrastra.', max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='mora_diaria_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mora fija en pesos por día para este préstamo. Si es null, se usa Configuracion.tasa_mora_diaria.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prestamorapido',
            name='capital_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo de capital vivo. Fuente única de verdad — no se reparte en las cuotas.', max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamorapido',
            name='interes_acumulado_sin_pagar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Interés de períodos anteriores que quedó sin pagar y se arrastra.', max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamorapido',
            name='mora_diaria_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mora fija en pesos por día para este préstamo. Si es null, se usa Configuracion.tasa_mora_diaria.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='dias_gracia_mora',
            field=models.IntegerField(default=2, help_text='Días de gracia antes de empezar a cobrar mora — mora arranca el día 3 de atraso.'),
        ),
    ]
