# Generated by Django 6.0 on 2025-12-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_cuota_options_remove_cuota_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='calendario_pagos',
            field=models.CharField(choices=[('5_21', '5 y 21 de cada mes'), ('15_30', '15 y 30 de cada mes')], default='15_30', max_length=10),
        ),
    ]
