# Generated by Django 4.2.30 on 2026-09-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_actualizar_dias_gracia_existente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIALMENTE_PAGADA', 'Parcialmente Pagada'), ('PAGADA', 'Completamente Pagada'), ('VENCIDA', 'Vencida sin Pago'), ('VENCIDA_PARCIAL', 'Vencida Parcialmente Pagada'), ('TRASLADADA', 'Trasladada a la Siguiente Cuota'), ('ANULADA', 'Anulada — el Crédito se Cerró Antes de Llegar Aquí')], default='PENDIENTE', help_text='Estado actual de la cuota', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuotarapida',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIALMENTE_PAGADA', 'Parcialmente Pagada'), ('PAGADA', 'Completamente Pagada'), ('VENCIDA', 'Vencida sin Pago'), ('VENCIDA_PARCIAL', 'Vencida Parcialmente Pagada'), ('TRASLADADA', 'Trasladada a la Siguiente Cuota'), ('ANULADA', 'Anulada — el Crédito se Cerró Antes de Llegar Aquí')], default='PENDIENTE', help_text='Estado actual de la cuota', max_length=20),
        ),
    ]
