# Generated by Django 6.0 on 2025-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_cliente_estado_cliente_fecha_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='notas_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado')], default='BORRADOR', max_length=20),
        ),
    ]
