# Generated by Django 6.0 on 2025-12-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_prestamo_fecha_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_pagado_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_pendiente_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
