# Generated by Django 6.0 on 2025-12-16 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_cuota_monto_pagado_interes_cuota_monto_pagado_mora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('usuario_registra', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mi_app.cuota')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
