# Generated by Django 6.0 on 2026-01-20 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_prestamo_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_interes_prestamo_normal', models.DecimalField(decimal_places=2, default=15.0, help_text='Tasa de interés anual para préstamos normales (%)', max_digits=5)),
                ('tasa_interes_prestamo_rapido', models.DecimalField(decimal_places=2, default=20.0, help_text='Tasa de interés anual para préstamos rápidos (%)', max_digits=5)),
                ('tasa_mora_diaria', models.DecimalField(decimal_places=2, default=2000, help_text='Mora diaria por cuota vencida', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='PrestamoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interes_porcentaje', models.DecimalField(decimal_places=2, help_text='Tasa de interés (%)', max_digits=5)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento (opcional)', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIALMENTE_PAGADO', 'Parcialmente Pagado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales (opcional)', null=True)),
                ('pagable_con_prestamo', models.BooleanField(default=False, help_text='¿Se paga junto con el préstamo regular o de forma externa?')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_rapidos', to='mi_app.cliente')),
            ],
            options={
                'verbose_name': 'Préstamo Rápido',
                'verbose_name_plural': 'Préstamos Rápidos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PagoPrestamoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('usuario_registra', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, help_text='Número de comprobante o referencia', max_length=100)),
                ('notas', models.TextField(blank=True, null=True)),
                ('prestamo_rapido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mi_app.prestamorapido')),
            ],
            options={
                'verbose_name': 'Pago Préstamo Rápido',
                'verbose_name_plural': 'Pagos Préstamos Rápidos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
