# Generated by Django 6.0 on 2026-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_configuracion_prestamorapido_pagoprestamorapido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
