# Generated by Django 6.0 on 2026-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_alter_cliente_cedula_alter_cliente_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='importado_excel',
            field=models.BooleanField(default=False),
        ),
    ]
