# Generated by Django 4.2.11 on 2026-01-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0015_alter_pagoprestamorapido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='dias_gracia_mora',
            field=models.IntegerField(default=5, help_text='Días de gracia antes de empezar a cobrar mora (PROBLEMA #12)'),
        ),
    ]
