# Generated by Django 4.2.11 on 2026-01-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_configuracion_dias_gracia_mora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamorapido',
            name='pagable_con_prestamo',
        ),
    ]
