# Generated by Django 4.2.11 on 2026-01-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0017_remove_prestamorapido_pagable_con_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIALMENTE_PAGADA', 'Parcialmente Pagada'), ('PAGADA', 'Completamente Pagada'), ('VENCIDA', 'Vencida sin Pago'), ('VENCIDA_PARCIAL', 'Vencida Parcialmente Pagada')], default='PENDIENTE', help_text='Estado actual de la cuota', max_length=20),
        ),
        migrations.AddField(
            model_name='cuota',
            name='porcentaje_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del monto original que ya se pagó (0-100)', max_digits=5),
        ),
    ]
