# Generated by Django 4.2.11 on 2026-01-31 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_app', '0018_cuota_estado_cuota_porcentaje_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='total_pagado',
        ),
        migrations.CreateModel(
            name='HistorioCambios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación'), ('CONDONAR', 'Condonación'), ('PAGAR', 'Pago'), ('REVERTIR', 'Reversión'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(db_index=True)),
                ('objeto_str', models.CharField(max_length=255)),
                ('campo_modificado', models.CharField(blank=True, max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('razon', models.CharField(blank=True, max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio',
                'verbose_name_plural': 'Auditoría de Cambios',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['usuario', '-fecha_cambio'], name='mi_app_hist_usuario_147249_idx'), models.Index(fields=['modelo', '-fecha_cambio'], name='mi_app_hist_modelo_86e5e0_idx'), models.Index(fields=['accion', '-fecha_cambio'], name='mi_app_hist_accion_0081f4_idx')],
            },
        ),
    ]
