# Generated by Django 6.0.2 on 2026-02-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0020_permiso_rol_alter_cliente_id_alter_configuracion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_mora_promedio',
            field=models.FloatField(default=0.0, help_text='Promedio de días de mora'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tasa_cumplimiento',
            field=models.FloatField(default=100.0, help_text='% de cuotas pagadas a tiempo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_pagado_historico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pagado HISTÓRICO', max_digits=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_prestado_historico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total acumulado HISTÓRICO (incluye préstamos eliminados)', max_digits=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_evaluacion',
            field=models.DateTimeField(blank=True, help_text='Última fecha de limpieza de histórico', null=True),
        ),
        migrations.CreateModel(
            name='ClienteScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prestado_acumulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pagado_acumulado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cuotas_pagadas_a_tiempo', models.IntegerField(default=0)),
                ('cuotas_vencidas', models.IntegerField(default=0)),
                ('tasa_cumplimiento', models.FloatField(default=100.0)),
                ('dias_mora_promedio', models.FloatField(default=0.0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('prestamos_limpiados', models.IntegerField(default=0, help_text='Cuántos préstamos se eliminaron en esta limpieza')),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_history', to='mi_app.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cliente Scorings',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
