# Generated by Django 6.0.2 on 2026-02-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0021_cliente_dias_mora_promedio_cliente_tasa_cumplimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto_original', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interes_normal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interes_mora_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago_esperada', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIALMENTE_PAGADA', 'Parcialmente Pagada'), ('PAGADA', 'Completamente Pagada'), ('VENCIDA', 'Vencida sin Pago'), ('VENCIDA_PARCIAL', 'Vencida Parcialmente Pagada')], default='PENDIENTE', help_text='Estado actual de la cuota', max_length=20)),
                ('porcentaje_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del monto original que ya se pagó (0-100)', max_digits=5)),
                ('monto_pagado_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pagado_interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pagado_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pendiente_interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prestamo_rapido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_rapidas', to='mi_app.prestamorapido')),
            ],
            options={
                'ordering': ['numero_cuota'],
            },
        ),
        migrations.AddField(
            model_name='pagoprestamorapido',
            name='cuota_rapida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='mi_app.cuotarapida'),
        ),
    ]
