# Generated by Django 6.0.2 on 2026-02-21 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0022_cuotarapida_pagoprestamorapido_cuota_rapida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoprestamorapido',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago Préstamo Rápido', 'verbose_name_plural': 'Pagos Préstamos Rápidos'},
        ),
        migrations.CreateModel(
            name='ListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('FRAUDE', 'Fraude'), ('MOROSO', 'Moroso'), ('COBRANZA', 'En cobranza judicial'), ('INCUMPLIMIENTO', 'Incumplimiento de contrato'), ('OTRO', 'Otro motivo')], default='OTRO', help_text='Razón por la que está en lista negra', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del motivo', null=True)),
                ('fecha_agregacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se agregó a la lista negra')),
                ('fecha_desde', models.DateField(help_text='Fecha a partir de la cual está en lista negra')),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual está en lista negra (si es temporal)', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la entrada en lista negra está activa')),
                ('importado_excel', models.BooleanField(default=False, help_text='Indica si fue importado desde Excel')),
                ('cliente', models.OneToOneField(help_text='Cliente en lista negra', on_delete=django.db.models.deletion.CASCADE, related_name='lista_negra', to='mi_app.cliente')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_negra_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada Lista Negra',
                'verbose_name_plural': 'Entradas Lista Negra',
                'ordering': ['-fecha_agregacion'],
                'indexes': [models.Index(fields=['cliente', 'activa'], name='mi_app_list_cliente_4450b5_idx'), models.Index(fields=['activa', 'fecha_desde'], name='mi_app_list_activa_d186c1_idx')],
            },
        ),
    ]
