# Generated by Django 6.0.2 on 2026-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0023_alter_pagoprestamorapido_options_listanegra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='etiqueta_cliente',
            field=models.CharField(choices=[('BUENO', 'Bueno'), ('MEDIO', 'Medio'), ('MALO', 'Malo'), ('SIN_HISTORIAL', 'Sin Historial')], default='SIN_HISTORIAL', help_text='Etiqueta automática: BUENO (95%+ cum, <5d mora), MEDIO (70-94%, 5-15d), MALO (<70%, >15d), SIN_HISTORIAL (sin préstamos)', max_length=15),
        ),
    ]
