# Generated by Django 6.0.2 on 2026-02-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0024_cliente_etiqueta_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_backup', models.CharField(choices=[('RAPIDO', 'Backup Rápido'), ('LOCAL', 'Guardar Local'), ('DESCARGA', 'Descarga Navegador'), ('CORREO', 'Envío Correo')], db_index=True, default='RAPIDO', max_length=20)),
                ('ubicacion', models.CharField(help_text='Dónde se guardó o envió (ej: /backups/, correo@cliente.com)', max_length=255)),
                ('nombre_archivo', models.CharField(help_text='Nombre del ZIP generado (ej: backup_20260221_144530.zip)', max_length=255)),
                ('tamano_mb', models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño en MB del archivo ZIP', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SUCCESS', 'Exitoso'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=20)),
                ('razon_error', models.TextField(blank=True, help_text='Descripción del error si falló')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('correo_destino', models.EmailField(blank=True, help_text='Email destino si se envió por correo', max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el backup')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Backup',
                'verbose_name_plural': 'Auditoría de Backups',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', '-fecha_inicio'], name='mi_app_audi_usuario_7844ef_idx'), models.Index(fields=['tipo_backup', '-fecha_inicio'], name='mi_app_audi_tipo_ba_64d90d_idx'), models.Index(fields=['estado', '-fecha_inicio'], name='mi_app_audi_estado_101d32_idx')],
            },
        ),
    ]
