# Generated by Django 6.0.2 on 2026-02-21 20:23
# FASE 2.2: Agregar índices de BD para optimizar queries (Task 8)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0025_auditoriabackup'),
    ]

    operations = [
        # Índice 1: Cuota (prestamo, pagado) - para filtrar cuotas rápidamente
        # Ejemplo de uso: Cuota.objects.filter(prestamo_id=X, pagado=False)
        # Impacto estimado: 100-200ms → 5-10ms
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['prestamo', 'pagado'], name='idx_cuota_prestamo_pagado'),
        ),
        
        # Índice 2: Prestamo (cliente, estado) - para listar por cliente y estado
        # Ejemplo de uso: Prestamo.objects.filter(cliente_id=X, estado='ACTIVO')
        # Impacto estimado: 50-100ms → 2-5ms
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['cliente', 'estado'], name='idx_prestamo_cliente_estado'),
        ),
        
        # Índice 4: Pago (fecha_pago) - para análisis históricos y reportes de pagos
        # Ejemplo de uso: Pago.objects.filter(fecha_pago__gte=fecha).order_by('-fecha_pago')
        # Impacto estimado: 20-40ms → 1-2ms
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['-fecha_pago'], name='idx_pago_fecha_pago'),
        ),
    ]

