# Generated by Django 6.0.2 on 2026-02-21 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0026_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('RESTORE', 'Restaurar')], db_index=True, help_text='Tipo de acción realizada', max_length=20)),
                ('modelo', models.CharField(choices=[('Cliente', 'Cliente'), ('Prestamo', 'Préstamo'), ('Cuota', 'Cuota'), ('Pago', 'Pago'), ('ListaNegra', 'Lista Negra'), ('Configuracion', 'Configuración'), ('User', 'Usuario')], db_index=True, help_text='Modelo/tabla afectada', max_length=50)),
                ('objeto_id', models.IntegerField(help_text='ID del objeto afectado')),
                ('objeto_representacion', models.CharField(blank=True, help_text='Representación legible del objeto (ej: Prestamo #123)', max_length=255)),
                ('cambios', models.JSONField(blank=True, help_text="JSON con cambios: {'campo': ['antes', 'después']}", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP de origen de la solicitud', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción legible en formato texto')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cuota',
            name='idx_cuota_prestamo_pagado',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='idx_pago_fecha_pago',
        ),
        migrations.RemoveIndex(
            model_name='prestamo',
            name='idx_prestamo_cliente_estado',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', '-timestamp'], name='mi_app_audi_usuario_92f0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['modelo', '-timestamp'], name='mi_app_audi_modelo_40d553_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['accion', '-timestamp'], name='mi_app_audi_accion_9d31ae_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['objeto_id', 'modelo'], name='mi_app_audi_objeto__fc41af_idx'),
        ),
    ]
